#services:
 # backend:
  #  image: ${BACKEND_IMAGE}
   # ports:
    #  - "5001:5000"
    #networks:
     # - app-network

  #frontend:
   # image: ${FRONTEND_IMAGE}
    #ports:
    #  - "8083:80"
    #depends_on:
    #  - backend
    #networks:
     # - app-network

#networks:
 # app-network:
  #  driver: bridge

services:
  backend:
    image: ${BACKEND_IMAGE}
    expose:
      - "5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    networks:
      - app-network

  frontend:
    image: ${FRONTEND_IMAGE}
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




#version: "3.9"

#services:
 # backend:
  #  image: ./backend
   # container_name: fastapi_backend
    #ports:
     # - "5001:5000"
#    networks:
 #    - app-network
#
 # frontend:
  #  build: ./frontend
   # container_name: nginx_frontend
    #ports:
     # - "8083:80"
    #depends_on:
     # - backend
    #networks:
     # - app-network

#networks:
 # app-network:
  #  driver: bridge
